#!/bin/bash
rsync -avzP cvm $1:/var/cos/cvm/
rsync -avzP cvm.c $1:/var/cos/cvm/
rsync -avzP exec $1:/var/cos/cvm/
rsync -avzP exec.c $1:/var/cos/cvm/
rsync -avzP initcvm.sh $1:/var/cos/cvm/
rsync -avzP monitor $1:/var/cos/cvm/
rsync -avzP monitor.c $1:/var/cos/cvm/
rsync -avzP autostart.php $1:/var/cos/cvm/
rsync -avzP cosconfig.xml $1:/var/cos/cvm/
rsync -avzP online $1:/var/cos/cvm/
rsync -avzP online.c $1:/var/cos/cvm/
rsync -avzP online.php $1:/var/cos/cvm/
rsync -avzP startonline.sh $1:/var/cos/cvm/
rsync -avzP startexec.sh $1:/var/cos/cvm/
rsync -avzP startcvm.sh $1:/var/cos/cvm/
rsync -avzP initcvm.sh $1:/var/cos/cvm/
rsync -avzP qemu-ifup $1:/var/cos/cvm/
rsync -avzP qemu-ifdown $1:/var/cos/cvm/
rsync -avzP qmp-shell $1:/var/cos/cvm/
rsync -avzP qmp.py $1:/var/cos/cvm/
